# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'Drone Safely' do

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Drone SafelyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
